/**
 * Supabase admin client for server-side database operations.
 * Uses the service role key to bypass RLS and perform direct queries.
 * This replaces Prisma ORM to avoid the table name mapping issue.
 *
 * The `Database` type is the authoritative shape generated by the Supabase
 * CLI from the live DB schema (`generate_typescript_types`). Regenerate it
 * after any migration: `supabase gen types typescript --project-id ...`.
 */
import { createClient, type SupabaseClient } from '@supabase/supabase-js';

// ─── Supabase-generated Database type ─────────────────────────────────────────

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: '14.5';
  };
  public: {
    Tables: {
      architectures: {
        Row: {
          created_at: string;
          features: Json;
          id: string;
          interfaces: Json;
          mcu: string | null;
          power: string | null;
          project_id: string;
          rationale: string | null;
          template_id: string;
          template_name: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          features: Json;
          id?: string;
          interfaces: Json;
          mcu?: string | null;
          power?: string | null;
          project_id: string;
          rationale?: string | null;
          template_id: string;
          template_name: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          features?: Json;
          id?: string;
          interfaces?: Json;
          mcu?: string | null;
          power?: string | null;
          project_id?: string;
          rationale?: string | null;
          template_id?: string;
          template_name?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'architectures_project_id_fkey';
            columns: ['project_id'];
            isOneToOne: false;
            referencedRelation: 'projects';
            referencedColumns: ['id'];
          },
        ];
      };
      audit_entries: {
        Row: {
          action: string;
          actor: string | null;
          category: string;
          created_at: string;
          details: Json | null;
          id: string;
          project_id: string;
          severity: string;
          source: string | null;
        };
        Insert: {
          action: string;
          actor?: string | null;
          category: string;
          created_at?: string;
          details?: Json | null;
          id?: string;
          project_id: string;
          severity?: string;
          source?: string | null;
        };
        Update: {
          action?: string;
          actor?: string | null;
          category?: string;
          created_at?: string;
          details?: Json | null;
          id?: string;
          project_id?: string;
          severity?: string;
          source?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'audit_entries_project_id_fkey';
            columns: ['project_id'];
            isOneToOne: false;
            referencedRelation: 'projects';
            referencedColumns: ['id'];
          },
        ];
      };
      bom_rows: {
        Row: {
          alternates: Json | null;
          bom_id: string;
          created_at: string;
          currency: string;
          description: string | null;
          id: string;
          is_estimate: boolean;
          lifecycle: string;
          manufacturer: string;
          mpn: string;
          package: string;
          provenance_source: string | null;
          provenance_url: string | null;
          quantity: number;
          ref: string;
          risk: string;
          unit_price: number;
          updated_at: string;
          value: string;
        };
        Insert: {
          alternates?: Json | null;
          bom_id: string;
          created_at?: string;
          currency?: string;
          description?: string | null;
          id?: string;
          is_estimate?: boolean;
          lifecycle?: string;
          manufacturer: string;
          mpn: string;
          package: string;
          provenance_source?: string | null;
          provenance_url?: string | null;
          quantity?: number;
          ref: string;
          risk?: string;
          unit_price?: number;
          updated_at?: string;
          value: string;
        };
        Update: {
          alternates?: Json | null;
          bom_id?: string;
          created_at?: string;
          currency?: string;
          description?: string | null;
          id?: string;
          is_estimate?: boolean;
          lifecycle?: string;
          manufacturer?: string;
          mpn?: string;
          package?: string;
          provenance_source?: string | null;
          provenance_url?: string | null;
          quantity?: number;
          ref?: string;
          risk?: string;
          unit_price?: number;
          updated_at?: string;
          value?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'bom_rows_bom_id_fkey';
            columns: ['bom_id'];
            isOneToOne: false;
            referencedRelation: 'boms';
            referencedColumns: ['id'];
          },
        ];
      };
      boms: {
        Row: {
          created_at: string;
          currency: string;
          id: string;
          is_estimate: boolean;
          line_count: number;
          project_id: string;
          total_cost: number;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          currency?: string;
          id?: string;
          is_estimate?: boolean;
          line_count?: number;
          project_id: string;
          total_cost?: number;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          currency?: string;
          id?: string;
          is_estimate?: boolean;
          line_count?: number;
          project_id?: string;
          total_cost?: number;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'boms_project_id_fkey';
            columns: ['project_id'];
            isOneToOne: false;
            referencedRelation: 'projects';
            referencedColumns: ['id'];
          },
        ];
      };
      design_artifacts: {
        Row: {
          artifact_type: string;
          checksum: string;
          created_at: string;
          file_name: string;
          file_path: string;
          file_size: number;
          id: string;
          metadata: Json | null;
          mime_type: string;
          project_id: string;
          storage_bucket: string;
          storage_key: string;
        };
        Insert: {
          artifact_type: string;
          checksum: string;
          created_at?: string;
          file_name: string;
          file_path: string;
          file_size: number;
          id?: string;
          metadata?: Json | null;
          mime_type: string;
          project_id: string;
          storage_bucket: string;
          storage_key: string;
        };
        Update: {
          artifact_type?: string;
          checksum?: string;
          created_at?: string;
          file_name?: string;
          file_path?: string;
          file_size?: number;
          id?: string;
          metadata?: Json | null;
          mime_type?: string;
          project_id?: string;
          storage_bucket?: string;
          storage_key?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'design_artifacts_project_id_fkey';
            columns: ['project_id'];
            isOneToOne: false;
            referencedRelation: 'projects';
            referencedColumns: ['id'];
          },
        ];
      };
      design_jobs: {
        Row: {
          completed_at: string | null;
          created_at: string;
          error: string | null;
          id: string;
          job_type: string;
          progress: number;
          project_id: string;
          result: Json | null;
          started_at: string | null;
          status: string;
          worker_id: string | null;
        };
        Insert: {
          completed_at?: string | null;
          created_at?: string;
          error?: string | null;
          id?: string;
          job_type: string;
          progress?: number;
          project_id: string;
          result?: Json | null;
          started_at?: string | null;
          status?: string;
          worker_id?: string | null;
        };
        Update: {
          completed_at?: string | null;
          created_at?: string;
          error?: string | null;
          id?: string;
          job_type?: string;
          progress?: number;
          project_id?: string;
          result?: Json | null;
          started_at?: string | null;
          status?: string;
          worker_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'design_jobs_project_id_fkey';
            columns: ['project_id'];
            isOneToOne: false;
            referencedRelation: 'projects';
            referencedColumns: ['id'];
          },
        ];
      };
      handoff_requests: {
        Row: {
          created_at: string;
          id: string;
          metadata: Json | null;
          project_id: string;
          quantity: number;
          quote_id: string | null;
          status: string;
          type: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          metadata?: Json | null;
          project_id: string;
          quantity?: number;
          quote_id?: string | null;
          status?: string;
          type: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          metadata?: Json | null;
          project_id?: string;
          quantity?: number;
          quote_id?: string | null;
          status?: string;
          type?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'handoff_requests_project_id_fkey';
            columns: ['project_id'];
            isOneToOne: false;
            referencedRelation: 'projects';
            referencedColumns: ['id'];
          },
        ];
      };
      ingestion_manifests: {
        Row: {
          candidate_families: Json;
          created_at: string;
          id: string;
          project_id: string;
          stages: Json;
          status: string;
          sufficiency_report: Json | null;
          updated_at: string;
        };
        Insert: {
          candidate_families: Json;
          created_at?: string;
          id?: string;
          project_id: string;
          stages: Json;
          status: string;
          sufficiency_report?: Json | null;
          updated_at?: string;
        };
        Update: {
          candidate_families?: Json;
          created_at?: string;
          id?: string;
          project_id?: string;
          stages?: Json;
          status?: string;
          sufficiency_report?: Json | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'ingestion_manifests_project_id_fkey';
            columns: ['project_id'];
            isOneToOne: false;
            referencedRelation: 'projects';
            referencedColumns: ['id'];
          },
        ];
      };
      intake_messages: {
        Row: {
          attachments: Json | null;
          content: string;
          created_at: string;
          id: string;
          project_id: string;
          role: string;
        };
        Insert: {
          attachments?: Json | null;
          content: string;
          created_at?: string;
          id?: string;
          project_id: string;
          role: string;
        };
        Update: {
          attachments?: Json | null;
          content?: string;
          created_at?: string;
          id?: string;
          project_id?: string;
          role?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'intake_messages_project_id_fkey';
            columns: ['project_id'];
            isOneToOne: false;
            referencedRelation: 'projects';
            referencedColumns: ['id'];
          },
        ];
      };
      organization_members: {
        Row: {
          created_at: string;
          id: string;
          organization_id: string;
          role: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          organization_id: string;
          role?: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          organization_id?: string;
          role?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'organization_members_organization_id_fkey';
            columns: ['organization_id'];
            isOneToOne: false;
            referencedRelation: 'organizations';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'organization_members_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      organizations: {
        Row: {
          created_at: string;
          id: string;
          name: string;
          plan: string;
          slug: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          name: string;
          plan?: string;
          slug: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          name?: string;
          plan?: string;
          slug?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      projects: {
        Row: {
          created_at: string;
          current_step: number;
          description: string | null;
          id: string;
          name: string;
          organization_id: string;
          status: string;
          total_steps: number;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          current_step?: number;
          description?: string | null;
          id?: string;
          name: string;
          organization_id: string;
          status?: string;
          total_steps?: number;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          current_step?: number;
          description?: string | null;
          id?: string;
          name?: string;
          organization_id?: string;
          status?: string;
          total_steps?: number;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'projects_organization_id_fkey';
            columns: ['organization_id'];
            isOneToOne: false;
            referencedRelation: 'organizations';
            referencedColumns: ['id'];
          },
        ];
      };
      quotes: {
        Row: {
          assumptions: Json;
          breakdown: Json;
          confidence: string;
          created_at: string;
          currency: string;
          high_quote: number;
          id: string;
          is_estimate: boolean;
          low_quote: number;
          mid_quote: number;
          project_id: string;
          quantity: number;
          updated_at: string;
        };
        Insert: {
          assumptions: Json;
          breakdown: Json;
          confidence: string;
          created_at?: string;
          currency?: string;
          high_quote: number;
          id?: string;
          is_estimate?: boolean;
          low_quote: number;
          mid_quote: number;
          project_id: string;
          quantity?: number;
          updated_at?: string;
        };
        Update: {
          assumptions?: Json;
          breakdown?: Json;
          confidence?: string;
          created_at?: string;
          currency?: string;
          high_quote?: number;
          id?: string;
          is_estimate?: boolean;
          low_quote?: number;
          mid_quote?: number;
          project_id?: string;
          quantity?: number;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'quotes_project_id_fkey';
            columns: ['project_id'];
            isOneToOne: false;
            referencedRelation: 'projects';
            referencedColumns: ['id'];
          },
        ];
      };
      specs: {
        Row: {
          compiled_at: string | null;
          constraints: Json;
          created_at: string;
          id: string;
          interfaces: Json;
          project_id: string;
          raw_text: string | null;
          requirements: Json;
          updated_at: string;
        };
        Insert: {
          compiled_at?: string | null;
          constraints: Json;
          created_at?: string;
          id?: string;
          interfaces: Json;
          project_id: string;
          raw_text?: string | null;
          requirements: Json;
          updated_at?: string;
        };
        Update: {
          compiled_at?: string | null;
          constraints?: Json;
          created_at?: string;
          id?: string;
          interfaces?: Json;
          project_id?: string;
          raw_text?: string | null;
          requirements?: Json;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'specs_project_id_fkey';
            columns: ['project_id'];
            isOneToOne: false;
            referencedRelation: 'projects';
            referencedColumns: ['id'];
          },
        ];
      };
      users: {
        Row: {
          avatar_url: string | null;
          created_at: string;
          email: string;
          full_name: string | null;
          id: string;
          supabase_user_id: string;
          updated_at: string;
        };
        Insert: {
          avatar_url?: string | null;
          created_at?: string;
          email: string;
          full_name?: string | null;
          id?: string;
          supabase_user_id: string;
          updated_at?: string;
        };
        Update: {
          avatar_url?: string | null;
          created_at?: string;
          email?: string;
          full_name?: string | null;
          id?: string;
          supabase_user_id?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      ensure_user_and_org: {
        Args: {
          p_email: string;
          p_full_name?: string;
          p_supabase_user_id: string;
        };
        Returns: {
          organization_id: string;
          user_id: string;
        }[];
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

// ─── Compatibility aliases for the previous hand-rolled interfaces ────────────
// Existing call sites import these names directly; derive them from the
// generated Database type so they stay in sync with migrations.

type PublicRow<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];

export type DbUser = PublicRow<'users'>;
export type DbOrganization = PublicRow<'organizations'>;
export type DbOrganizationMember = PublicRow<'organization_members'>;
export type DbProject = PublicRow<'projects'>;
export type DbIntakeMessage = PublicRow<'intake_messages'>;
export type DbSpec = PublicRow<'specs'>;
export type DbArchitecture = PublicRow<'architectures'>;
export type DbBOM = PublicRow<'boms'>;
export type DbBOMRow = PublicRow<'bom_rows'>;
export type DbQuote = PublicRow<'quotes'>;
export type DbIngestionManifest = PublicRow<'ingestion_manifests'>;
export type DbDesignArtifact = PublicRow<'design_artifacts'>;
export type DbDesignJob = PublicRow<'design_jobs'>;
export type DbHandoffRequest = PublicRow<'handoff_requests'>;
export type DbAuditEntry = PublicRow<'audit_entries'>;

// ─── Client singleton ─────────────────────────────────────────────────────────

let _adminClient: SupabaseClient<Database> | null = null;

export function getSupabaseAdmin(): SupabaseClient<Database> {
  if (_adminClient) return _adminClient;

  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!url || !key) {
    throw new Error('Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY');
  }

  _adminClient = createClient<Database>(url, key, {
    auth: {
      autoRefreshToken: false,
      persistSession: false,
    },
  });

  return _adminClient;
}
