import type { SeedConfig } from '../pipeline/types';

export const BOOTSTRAP_SEED: SeedConfig = {
  version: '0.1.0',
  description: 'Bootstrap default seed configuration for Raino ingestion',
  families: [
    {
      family: 'STM32F4',
      manufacturer: 'STMicroelectronics',
      mpns: ['STM32F407VGT6', 'STM32F401CCU6'],
      requiredDocTypes: ['datasheet', 'errata', 'app_note', 'package_doc'],
      expectsErrata: true,
      requiresPackageDocs: true,
      requiresAlternates: true,
      retrievalLabels: ['MCU', 'ARM Cortex-M4', 'STM32F4', 'microcontroller'],
    },
    {
      family: 'ESP32-S3',
      manufacturer: 'Espressif',
      mpns: ['ESP32-S3-WROOM-1-N8R8', 'ESP32-S3-WROOM-1-N8'],
      requiredDocTypes: ['datasheet', 'app_note'],
      expectsErrata: false,
      requiresPackageDocs: true,
      requiresAlternates: true,
      retrievalLabels: ['MCU', 'WiFi', 'BLE', 'ESP32', 'IoT'],
    },
    {
      family: 'LM78xx',
      manufacturer: 'Texas Instruments',
      mpns: ['LM7805CT'],
      requiredDocTypes: ['datasheet'],
      expectsErrata: false,
      requiresPackageDocs: false,
      requiresAlternates: true,
      retrievalLabels: ['regulator', 'linear', 'LDO', '5V'],
    },
    {
      family: 'USB-C',
      manufacturer: 'Amphenol',
      mpns: ['USB4105-GF-A'],
      requiredDocTypes: ['datasheet'],
      expectsErrata: false,
      requiresPackageDocs: true,
      requiresAlternates: true,
      retrievalLabels: ['USB', 'USB-C', 'connector'],
    },
    {
      family: 'PRTR5V0U2X',
      manufacturer: 'NXP',
      mpns: ['PRTR5V0U2X'],
      requiredDocTypes: ['datasheet'],
      expectsErrata: false,
      requiresPackageDocs: false,
      requiresAlternates: false,
      retrievalLabels: ['ESD', 'protection', 'USB', 'TVS'],
    },
    {
      family: 'ABM8',
      manufacturer: 'Abracon',
      mpns: ['ABM8-16.000MHZ-B2-T'],
      requiredDocTypes: ['datasheet'],
      expectsErrata: false,
      requiresPackageDocs: false,
      requiresAlternates: true,
      retrievalLabels: ['crystal', 'oscillator', 'clock', '16MHz'],
    },
  ],
  sourcePreferences: [
    { domain: 'st.com', trustLevel: 'canonical' },
    { domain: 'espressif.com', trustLevel: 'canonical' },
    { domain: 'ti.com', trustLevel: 'canonical' },
    { domain: 'nxp.com', trustLevel: 'canonical' },
    { domain: 'abracon.com', trustLevel: 'canonical' },
  ],
};
